// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace KlipWorksApp
{
	public partial class KlipsListController : UIViewController
	{
		public KlipsListController(IntPtr handle) : base (handle) {
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			if(AppDelegate.model.inspectedVideoProject == null) TableView.Source = new TableSource(this, AppDelegate.model.getKlips());
			else TableView.Source = new TableSource(this, AppDelegate.model.inspectedVideoProject.klips);
		}

		private class TableSource : UITableViewSource
		{
			List<Klip> TableItems;
			string CellIdentifier = "ClipCell";
			KlipsListController projectsListController;

			public TableSource(KlipsListController projectsListController, List<Klip> items)
			{
				this.projectsListController = projectsListController;
				TableItems = items;
			}

			public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
			{

				ClipTableCell cell = (ClipTableCell) tableView.DequeueReusableCell(CellIdentifier);
				Klip item = TableItems[indexPath.Row];

				if (cell == null) cell = new ClipTableCell(new NSString(CellIdentifier));
				cell.UpdateCell(item);

				return cell;
			}

			public override nint RowsInSection(UITableView tableview, nint section) { return TableItems.Count; }
		}
	}
}
