// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace KlipWorksApp
{
	public partial class KlipsListController : UIViewController
	{
		public KlipsListController(IntPtr handle) : base (handle) {
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			TabelView.Source = new TableSource(this, AppDelegate.model.getKlips());
		}

		private class TableSource : UITableViewSource
		{
			List<Klip> TableItems;
			string CellIdentifier = "TableCell";
			KlipsListController projectsListController;

			public TableSource(KlipsListController projectsListController, List<Klip> items)
			{
				this.projectsListController = projectsListController;
				TableItems = items;
			}

			public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
			{

				UITableViewCell cell = tableView.DequeueReusableCell(CellIdentifier);
				Klip item = TableItems[indexPath.Row];

				if (cell == null) cell = new UITableViewCell();
				cell.TextLabel.Text = item.name + ", " + item.duration.ToString("hh\\:mm\\:ss");

				return cell;
			}

			public override nint RowsInSection(UITableView tableview, nint section) { return TableItems.Count; }
		}
	}
}
